//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vrooms.Domain.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Language
    {
        public Language()
        {
            this.Books = new HashSet<Book>();
        }
    
        public int LanguageId { get; set; }
        public string Iso3 { get; set; }
        public string LanguageName_En { get; set; }
    
        public virtual ICollection<Book> Books { get; set; }
    }
}
