//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vrooms.Domain.Entities
{
    using System;
    
    public enum CirculationStatuses : int
    {
        ReferenceOnly = 1,
        InProcess = 2,
        Available = 3,
        Reserved = 4,
        CheckedOut = 5,
        Lost = 6
    }
}
