//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vrooms.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReservedBookItem
    {
        public int ReservedBookItemId { get; set; }
        public int BookItemId { get; set; }
        public int PatronId { get; set; }
        public System.DateTime DateReserved { get; set; }
    
        public virtual BookItem BookItem { get; set; }
        public virtual Patron Patron { get; set; }
    }
}
